import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <aside className="w-full flex-none md:w-6">
          <nav>
            <ul>
              <li><Link href="/">home</Link></li>
              <li><Link href="/tasks">Tasks</Link></li>
              <li><Link href="/projects">Projects</Link></li>
            </ul>
          </nav>
        </aside>
        <main className="flex-grow p-6 md:overflow-y-auto md:p-12">
        {children}
        </main>
      </body>
    </html>
  );
}
